[package]
name = "wgpu_life"
version = "0.1.0"
authors = ["rusty shackleford"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.9"
winit = "0.22.2"
futures = "0.3.5"
wgpu = "0.6.0"
shaderc = "0.6.2"